---
language: go
sudo: false
go:
  - "1.13"
  - "1.14"
  - tip
jobs:
  fast_finish: true
  allow_failures:
    - go: tip
branches:
  # don't build pull requests twice
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
script:
  - make coverage
  - make vet
